name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - name: latest
            dockerfile: Dockerfile
          - name: lts
            dockerfile: Dockerfile.lts
          - name: 18
            dockerfile: Dockerfile.18
          - name: 16
            dockerfile: Dockerfile.16
          - name: 14
            dockerfile: Dockerfile.14
          - name: 12
            dockerfile: Dockerfile.12
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: rambabusaravanan/firebase

    - name: Build and Push Docker Image (node:${{ matrix.variant.name }})
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ matrix.variant.dockerfile }}
        push: true
        tags: rambabusaravanan/firebase:${{ matrix.variant.name }}
        labels: ${{ steps.meta.outputs.labels }}
